### ISSUE TITLE
bbcmicrobot handle not removed when CAPS used?

### ISSUE THREAD

**Issue by 8bitkick** [8bitkick/BBCMicroBot#15]
Eg https://twitter.com/bbcmicrobot/status/1274799303907737606?s=21

Suspect there’s a case sensitive regex or string comparison in there need to take a look

**Comment by ojwb** [comment]
`remove_first_occurrence()` does an `indexOf()` substring search - presumably `screen_name` in `tweet.entities.user_mentions` is lower-cased?

Probably it would be better to use the `indices` from that to decide what to delete instead.

**Comment by ojwb** [comment]
I'm happy to try to come up with a patch for this if that would be useful, but I think I'd really need a dump of the JSON from a sample tweet to test with (ideally one with multiple users mentioned).

**Comment by ojwb** [comment]
This continues to trip people up from time to time so would be good to fix.

@8bitkick Can you easily capture the JSON for a tweet with multiple users mentioned?  I could write a patch without one, but it'd be easier with a real input to test against.
