### ISSUE TITLE
PNG output?

### ISSUE THREAD

**Issue by ojwb** [8bitkick/BBCMicroBot#2]
The bot code in the repo will generate a PNG if all captured frames are the same, and the tests seem to show that works.

However, the live bot doesn't seem to do this.  For example, this is a static image but produced a video:

https://twitter.com/Kweepa/status/1272280506114211841

However if I copy that code into a new test then I do get a PNG!

Is the live code different to the code in this repo?

**Comment by 8bitkick** [comment]
Hah! You're a little quicker than I expected - yes I uploaded to this repo with the PNG enhancement in there - but have not created an action to auto deploy yet. The live version is behind right now but I will keep in sync'ed in future.

**Comment by 8bitkick** [comment]
@ojwb I've sync'ed the live version now and had the bot re-run that tweet. Here's the PNG output. 

https://twitter.com/bbcmicrobot/status/1272367497623171072

An aside. I'm not totally sure I like the fact that Twitter seems to crop a letterbox timeline preview of the PNG - this doesn't happen to video.

**Comment by ojwb** [comment]
Heh, I was just writing a reply to close this.

Producing an image for a static result seems a nice idea, but the cropping is very annoying.

Perhaps a static GIF would avoid this?  At least the old animated GIF output wasn't cropped like this AFAICR, though maybe twitter has changed, or perhaps it handles animated and static GIFs differently.

**Comment by 8bitkick** [comment]
Good idea a 2 frame animated GIF could work. The original reason for the PNG is some static 'hi res' MODE 0 graphics appear blurred in the timeline in the video preview, I was trying to avoid that.

**Comment by 8bitkick** [comment]
We should see how the PNG goes. Might be GIF is better. Need to test.

**Comment by ojwb** [comment]
Another issue here is that any audio is now lost if a PNG image is generated.  I have a working fix for that, but I need to sort out test cases.

It also avoids pointlessly encoding a silent audio stream into the video, which gives a smaller video for such cases (which seem to be the majority of tweets).

**Comment by ojwb** [comment]
> We should see how the PNG goes. Might be GIF is better. Need to test.

I tried making a GIF via "try" with the obvious code tweak to see how it looks in the timeline but twitter won't let me tweet it with the uselessly vague error:

```
Something went wrong, but don’t fret — let’s give it another shot.
```

**Comment by 8bitkick** [comment]
Do you have a Twitter Dev account + created a new app + put the API keys for the app in the BBC Micro .env? If so perhaps Twitter prefers a GIF to uploaded via simple Media Upload method https://developer.twitter.com/en/docs/tutorials/uploading-media

**Comment by ojwb** [comment]
I have/did none of those things!

I just tried to attach the GIF to a tweet via the web UI (since I thought that would show if it got a letterboxed preview in the timeline, and if it did I could then try with a 2 frame GIF to see if that was treated better).  But twitter wasn't letting me post it for unclear reasons.

**Comment by ojwb** [comment]
A smaller GIF (with 2 frames, both the same) seems to get shown in full: https://twitter.com/rheolism/status/1272780741110165504

**Comment by 8bitkick** [comment]
Cool. We need a dev twitter account you can access will get it sorted this weekend

**Comment by 8bitkick** [comment]
Thread summary: The PNG isn’t generated for static image without audio. And it should probably generate a 2 frame GIF anyhow

**Comment by ojwb** [comment]
It seems that behind the scenes twitter actually converts a GIF to a video and serves that instead.  I suspect the rejection of a static GIF is probably that video conversion step failing.

But that may mean that GIF isn't any better for avoiding the blurred MODE0 graphics issue, because twitter's conversion will reintroduce that problem.

I'm not sure why PNGs aren't being produced though.  Perhaps my "cmp with /dev/zero" trick doesn't give the expected output on the live machine and so it thinks there is audio?

**Comment by 8bitkick** [comment]
The `cmp` trick might be the problem. Production is running on AWS EC2 / Amazon Linux AMI... CentOS like? Some commands differ eg `shasum` becomes `sha1sum`

**Comment by ojwb** [comment]
Rather than try to find out, I just rewrote the code to avoid using external commands for this (#10).

**Comment by 8bitkick** [comment]
This works fine now. Whether we want to switch from PNG to GIF is another issue
