### ISSUE TITLE
Tokenize parse error kills client

### ISSUE THREAD

**Issue by 8bitkick** [8bitkick/BBCMicroBot#27]
As noted by @ojwb and described here 
https://twitter.com/bbcmicrobot/status/1307147917065506816?s=20

**Comment by ojwb** [comment]
I actually already fixed this locally but then was distracted before
opening a PR.  Will push tomorrow.

**Comment by 8bitkick** [comment]
Awesome thanks. I think the online bot lags a version too so I need to update anyhow
