### ISSUE TITLE
User Guide review

### ISSUE THREAD

**Issue by 8bitkick** [8bitkick/BBCMicroBot#42]
@ojwb take a look at this in particular the second half on minification tricks. The me know if you spot any inaccuracies / omissions. It's a write up of some of your stuff in fact!

https://github.com/8bitkick/BBCMicroBot/blob/master/docs/user%20guide.md

**Comment by ojwb** [comment]
I've pushed fixes for some typos, and also to show abbreviating `GOTO` as well as `PRINT` for a better demonstration of abbreviations vs tokens.  Otherwise looks good.

**Comment by ojwb** [comment]
Pushing a doc-only change failed CI which looks unrelated.  Investigating it looks to be due to beebjit changes and so I've also pushed a change to fix that (beebjit now handles the NOVSYNC testcase better, so I just updated the expected results to match).
